name: expanded-owls-windows-test
on:
  push:
    branches:
      - expanded-owls-room-assets
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-2ship-otr:
    runs-on: ubuntu-22.04
    steps:
    - name: Git Checkout
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y $(cat .github/workflows/apt-deps.txt) libzip-dev zipcmp zipmerge ziptool
    - name: Generate 2ship.o2r
      run: |
        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release
        cmake --build build-cmake --config Release --target Generate2ShipOtr -j3
    - name: Upload 2ship.o2r
      uses: actions/upload-artifact@v7
      with:
        name: 2ship.o2r
        path: 2ship.o2r
        retention-days: 3

  build-windows:
    needs: generate-2ship-otr
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
        choco install ninja -y
        Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force -ErrorAction SilentlyContinue
    - name: Git Checkout
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Configure Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
    - name: Download 2ship.o2r
      uses: actions/download-artifact@v8
      with:
        name: 2ship.o2r
        path: build-windows/mm
    - name: Build 2Ship
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      run: |
        set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
        cmake -S . -B build-windows -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release
        cmake --build build-windows --config Release --parallel 10
        (cd build-windows && cpack)
        cd ..
        mv _packages/*.zip _packages/2ship-windows.zip
    - name: Unzip package
      run: Expand-Archive -Path _packages/2ship-windows.zip -DestinationPath 2ship-windows
    - name: Upload runnable Windows test build
      uses: actions/upload-artifact@v7
      with:
        name: expanded-owls-windows-test
        path: 2ship-windows
        retention-days: 7
